In [1]:
import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

In [2]:
ticker = "SPY"
start_date = "2010-01-01"

df = yf.download(ticker, start=start_date)

df.head()

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open     Volume
Ticker            SPY        SPY        SPY        SPY        SPY
Date
2010-01-04  85.027939  85.072953  83.662450  84.307682  118944600
2010-01-05  85.253044  85.290560  84.667835  84.975448  111579900
2010-01-06  85.313049  85.523124  85.102975  85.170496  116074400
2010-01-07  85.673180  85.778217  84.915407  85.155492  131091100
2010-01-08  85.958252  85.995768  85.275511  85.448069  126402800

In [3]:
df = df[["Close"]].dropna()

In [4]:
df.tail()

Price            Close
Ticker             SPY
Date
2026-03-02  686.380005
2026-03-03  680.330017
2026-03-04  685.130005
2026-03-05  681.309998
2026-03-06  672.380005

In [5]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 4068 entries, 2010-01-04 to 2026-03-06
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   (Close, SPY)  4068 non-null   float64
dtypes: float64(1)
memory usage: 63.6 KB

In [7]:
df["log_return"] = np.log(df["Close"]).diff()

df = df.dropna()

df.head()

Price           Close log_return
Ticker            SPY
Date
2010-01-05  85.253044   0.002644
2010-01-06  85.313049   0.000704
2010-01-07  85.673180   0.004212
2010-01-08  85.958252   0.003322
2010-01-11  86.078339   0.001396

# Rolling volatility

In [8]:
df["volatility_20"] = df["log_return"].rolling(20).std()

# trend and momentum indicators

In [9]:
df["ma_50"] = df["Close"].rolling(50).mean()
df["ma_200"] = df["Close"].rolling(200).mean()

df["trend"] = df["ma_50"] - df["ma_200"]

In [10]:
df["momentum_10"] = df["Close"].pct_change(10)

# drawdown calculatin

In [11]:
df["drawdown"] = df["Close"] / df["Close"].cummax() - 1

# Clean Dataset

In [12]:
df.isnull().sum()

Price          Ticker
Close          SPY         0
log_return                 0
volatility_20             19
ma_50                     49
ma_200                   199
trend                    199
momentum_10               10
drawdown                   0
dtype: int64

In [13]:
df

Price,Close,log_return,volatility_20,ma_50,ma_200,trend,momentum_10,drawdown
Ticker,SPY,,,,,,,
Date,,,,,,,,
2010-01-05,85.253044,0.002644,NaN,NaN,NaN,NaN,NaN,0.000000
2010-01-06,85.313049,0.000704,NaN,NaN,NaN,NaN,NaN,0.000000
2010-01-07,85.673180,0.004212,NaN,NaN,NaN,NaN,NaN,0.000000
2010-01-08,85.958252,0.003322,NaN,NaN,NaN,NaN,NaN,0.000000
2010-01-11,86.078339,0.001396,NaN,NaN,NaN,NaN,NaN,0.000000
...,...,...,...,...,...,...,...,...
2026-03-02,686.380005,0.000568,0.008204,687.853374,652.265374,35.588000,0.006791,-0.013099
2026-03-03,680.330017,-0.008853,0.008309,688.071536,652.754439,35.317096,-0.003690,-0.021798
2026-03-04,685.130005,0.007031,0.008307,688.284597,653.253278,35.031319,-0.001690,-0.014896
2026-03-05,681.309998,-0.005591,0.008330,688.298997,653.714479,34.584518,-0.004631,-0.020388
2026-03-06,672.380005,-0.013194,0.008379,688.049996,654.127807,33.922189,-0.024731,-0.033228

In [14]:
df = df.dropna()

df.describe()

Price,Close,log_return,volatility_20,ma_50,ma_200,trend,momentum_10,drawdown
Ticker,SPY,,,,,,,
count,3868.000000,3868.000000,3868.000000,3868.000000,3868.000000,3868.000000,3868.000000,3868.000000
mean,283.090331,0.000520,0.009127,279.286197,267.974868,11.311329,0.005743,-0.037393
std,159.274174,0.010765,0.005829,156.485716,148.075672,16.205468,0.029848,0.050860
min,85.319351,-0.115886,0.002007,84.982190,84.739096,-39.678090,-0.232884,-0.337173
25%,160.759575,-0.003651,0.005746,161.085845,153.022268,4.256445,-0.007563,-0.050922
50%,240.754486,0.000701,0.007605,239.221137,234.885681,8.491425,0.008155,-0.015239
75%,395.111404,0.005744,0.010644,389.014200,384.716584,17.243544,0.022496,-0.002662
max,695.489990,0.099863,0.059167,688.298997,654.127807,57.280704,0.187979,0.000000