In [1]:
import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

In [2]:
ticker = "SPY"
start_date = "2010-01-01"

df = yf.download(ticker, start=start_date)

df.head()

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open     Volume
Ticker            SPY        SPY        SPY        SPY        SPY
Date
2010-01-04  85.027939  85.072953  83.662450  84.307682  118944600
2010-01-05  85.253044  85.290560  84.667835  84.975448  111579900
2010-01-06  85.313049  85.523124  85.102975  85.170496  116074400
2010-01-07  85.673180  85.778217  84.915407  85.155492  131091100
2010-01-08  85.958252  85.995768  85.275511  85.448069  126402800

In [3]:
df = df[["Close"]].dropna()

In [4]:
df.tail()

Price            Close
Ticker             SPY
Date
2026-03-02  686.380005
2026-03-03  680.330017
2026-03-04  685.130005
2026-03-05  681.309998
2026-03-06  672.380005

In [5]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 4068 entries, 2010-01-04 to 2026-03-06
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   (Close, SPY)  4068 non-null   float64
dtypes: float64(1)
memory usage: 63.6 KB